apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "100"
    spec:
      serviceAccountName: backend-sa
      containers:
        - image: gcr.io/voicecare-prod/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri
